<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>03_准备_error.html</title>
</head>

<body>
  <script type="text/javascript">
    /*
      进一步理解JS中的错误(Error)和相关处理

      1. 错误的类型
        Error：所有错误的父类型
        ReferenceError：引用的变量不存在
        TypeError：类型错误
        RangeError：数据值不在其所允许的范围内
        SyntaxError：语法错误

      2. 错误处理
        捕获错误：try...catch
        抛出错误：throw error

      3. 错误对象
        message属性：错误相关信息
        stack属性：函数调用栈记录
    */

    // 1. 常见的内置错误

    // ReferenceError：引用的变量不存在
    console.log(a) // ReferenceError: a is not defined
    console.log('-----') // 没有捕获error，下面的代码不会执行

    // TypeError：类型错误
    let b = null
    console.log(b.xxx) // TypeError: Cannot read property 'xxx' of null
    let f = {}
    f.xxx() // TypeError: f.xxx is not a function

    // RangeError：数据值不在其所允许的范围内
    function fn() {
      fn()
    }
    fn() // RangeError: Maximum call stack size exceeded

    // SyntaxError：语法错误
    const c = """" // SyntaxError: Unexpected string

    // 2. 错误处理
    //   捕获错误：try...catch
    try {
      let d
      console.log(d.xxx)
    } catch (error) {
      console.dir(error)
      console.log(error.message)
      console.log(error.stack)
    }
    console.log('after error') // 捕获之后之后的代码任能执行

    //   抛出错误：throw error
    function foo() {
      if (Date.now() % 2 === 1) {
        console.log('当前时间为奇数，可以执行函数')
      } else { // 如果时间是偶数抛出异常，有调用者来处理
        throw new Error('当前时间为偶数，不能执行函数')
      }
    }
    try {
      foo()
    } catch (error) {
      console.dir(error)
    }
  </script>
</body>

</html>